name: Publishing to GitHub Packages

on:
  push:

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        run: echo "Build Packages"

  publish:
    name: ${{ matrix.ARGS.name }}
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        ARGS: [ 'package1', 'package2', 'package3' ]
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Run publish
        run: exit 1

  notify:
    runs-on: ubuntu-latest
    name: Send notifications
    needs: [build, publish]
    if: contains(needs.*.result, 'failure')

    steps:
      - name: Test notifications
        run: echo "Notification!"
