name: Publishing to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      filter:
        type: string
        description: Package file filter pattern
        required: false
      timestamp-version:
        type: boolean
        description: Set timestamp version
        required: false
        default: true
      next-tag:
        type: boolean
        description: Move 'next' tag
        required: false
        default: true
      stable-tag:
        type: boolean
        description: Move 'stable' tag
        required: false
        default: false

env:
  FILTER: ${{ github.event_name == 'workflow_dispatch' && inputs.filter || '' }}
  SET_TIMESTAMP_VERSION: ${{ (github.event_name == 'workflow_dispatch' && inputs.timestamp-version) || (github.event_name != 'workflow_dispatch' && true) }}
  MOVE_NEXT_TAG: ${{ (github.event_name == 'workflow_dispatch' && inputs.next-tag) || (github.event_name != 'workflow_dispatch' && true) }}
  MOVE_STABLE_TAG: ${{ (github.event_name == 'workflow_dispatch' && inputs.stable-tag) || (github.event_name != 'workflow_dispatch' && false) }}

jobs:

  build:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v4
